# -*- coding: utf-8 -*-
from __future__ import unicode_literals

class CSS_Paths:
	# Misc paths
	Misc_Logo = "html.js.borderimage.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing.ng-scope div.wrapper header div.inner-wrapper div.logo"
	Misc_X_Of_Merchan = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-interstitial.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.ng-scope header.win-head ul.list-btn.sprite li a.btn-red.icon-26x26-close"
	Misc_Dispensar = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-attention.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.ng-scope footer.win-foot ul.list-btn.list-center li.ng-scope a.btn-border.ng-binding.btn-green"
	Misc_Collect_Reward = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-daily-login-bonus.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.ng-scope footer.win-foot.sprite-fill ul.list-btn.list-center li a.btn-border.btn-premium.btn-orange.ng-binding"


	# Login related
	Login_Username = "html.js.borderimage.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing.ng-scope div.wrapper header div.inner-wrapper div.container.simple-wood-frame.login-container div.login-big.expanded div form.ng-pristine.ng-valid div.input.user input.ng-pristine.ng-untouched.ng-valid"
	Login_Password = "html.js.borderimage.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing.ng-scope div.wrapper header div.inner-wrapper div.container.simple-wood-frame.login-container div.login-big.expanded div form.ng-pristine.ng-valid div.input.pw input.ng-pristine.ng-untouched.ng-valid"
	Login_Button = "html.js.borderimage.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing.ng-scope div.wrapper header div.inner-wrapper div.container.simple-wood-frame.login-container div.login-big.expanded div form.ng-pristine.ng-valid button.button-login"

	Login_WorldsList = "html.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing-main.landing.ng-scope div#wrapper div.inner div.register.ng-scope div.container div.player-worlds.ng-scope div.menu"
	Login_FirstWorld = "html.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body div.landing-main.landing.ng-scope div#wrapper div.inner div.register.ng-scope div.container div.player-worlds.ng-scope div.container-inner div.inner-content ul.list-btn.list-center li.ng-scope a.btn-orange.btn-border.small-icon"


	# Build related
	Build_BoxPaper = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper.window-open section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix"
	Build_Finish_Build = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#toolbar-right.ng-scope div#interface-building-queue div.widget-interface-queue.interface-building-queue.ng-scope ul.progress li.ng-scope div.finish-slide.finish-visible div.finish-free-wrapper div.expanded-wrapper a.size-34x34.btn-green.icon-26x26-check-positive.animation-glow-green"
	Build_PageX = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.ng-scope header.win-head ul.list-btn li a.size-34x34.btn-red.icon-26x26-close"
	Build_ScrollBar = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper.window-open section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div div.jssb-y div.jssb-y-track div.jssb-y-thumb div.scrollbar-middle"

	Build_HeadQuarter =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-headquarter div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"
	Build_TimberCamp =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-timber_camp div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"
	Build_ClayPit =		"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-clay_pit div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"
	Build_IronMine =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-iron_mine div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"

	Build_Farm =		"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-farm div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"
	Build_Warehouse =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-warehouse div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"
	Build_RallyPoint =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-rally_point div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"

	Build_Barracks =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-headquarter.twx-window.screen.left div.win-content.ng-scope div.win-main.jssb-applied.jssb-scrolly.jssb-focus div.box-paper div.scroll-wrap div.ng-scope div.clearfix div.building-container.building-barracks div.ng-scope div.ng-scope table.tbl-border-dark.tbl-unit tbody tr td.button-list.ng-scope span.size-44x44.btn-upgrade.btn-orange"


	# Globe related
	Globe_Button = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper footer#interface-bottom-container div#interface-bottom.ng-scope div#interface-bottom-center a#world-map.btn-orange.icon-44x44-view-worldmap"
	Globe_Coord = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper footer#interface-bottom-container div#interface-bottom.ng-scope div#interface-bottom-center div#world-map-search-wrapper.ng-scope div.directive-world-map-search.box-border-dark.box-wrapper.visible div table.tbl-border-light.coordinates tbody tr"
	Globe_Search = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper footer#interface-bottom-container div#interface-bottom.ng-scope div#interface-bottom-center div#world-map-search-wrapper.ng-scope div.box-border-dark.box-wrapper.visible div table.tbl-border-light.coordinates tbody tr td div.size-34x34.btn-orange.icon-34x34-jump-to.float-right"

	# Village related
	Village_ViewButton = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper footer#interface-bottom-container div#interface-bottom.ng-scope div#interface-bottom-center a#village-zoom.btn-orange.icon-44x44-view-village"
	Village_Name = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div.info-wrapper div#info-town.info-box h4 div#village-name.ng-binding"


	# Resources related
#	Resources_Wood = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div#resource-bar div#resources-wrapper div.resource div.resource-values div.resource-text.ng-binding"
#	Resources_Boosted_Wood = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div#resource-bar div#resources-wrapper div.resource.boosted div.resource-values div.resource-text.ng-binding"
#	Resources_Clay = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div#resource-bar div#resources-wrapper div.resource div.resource-values div.resource-text.ng-binding"
#	Resources_Iron = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div#resource-bar div#resources-wrapper div.resource div.resource-values div.resource-text.ng-binding"


	# Rally Point GUI
	RallyPoint_Menu =			"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper.window-open section.building-rally-point.twx-window.screen.left div.win-content.ng-scope div.win-main.win-main-rally-point.jssb-applied.jssb-focus div.box-paper.footer"
	RallyPoint_NameMenu =		"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-preset-name.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.name_preset.ng-scope"
	RallyPoint_WriteDefName =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.building-rally-point.twx-window.screen.left div.win-content.ng-scope div.win-main.win-main-rally-point.jssb-applied div.box-paper.footer div.scroll-wrap div.ng-scope div.bottom-buttons ul.list-btn.list-center li a.btn-orange.btn-border.ng-binding"
	RallyPoint_SaveDefBtn =		"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-preset-name.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.name_preset.ng-scope footer.win-foot.sprite-fill ul.list-btn.list-center li a.btn-orange.btn-border.ng-binding"
	RallyPoint_FlagCreating =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-icon-generator.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.ng-scope.preset"
	RallyPoint_CreateMenu =		"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-preset-edit.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.preset-edit.ng-scope"
	RallyPoint_GlobalPredefs =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div.modal-load-preset-list.twx-modal.modal div.outer-wrapper div.middle-wrapper div.inner-wrapper div.win-content.ng-scope div.win-main.jssb-applied.jssb-focus div.box-paper div.scroll-wrap div table#preset-list.tbl-border-light.tbl-striped tbody"

#	RallyPoint_ =

	# Unit quantity related
	UnitQuant_UnitBar = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#topinterface-right-wrapper.ng-scope div#unit-bar"
	UnitQuant_UnitMenu = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper.window-open.window-fullsize section.screen-unit-overview.twx-window.screen.fullsize.left div.win-content.screen-unit-list.ng-scope div.win-main.jssb-applied.jssb-focus.jssb-scrolly div.outer-scroll-wrap div.scroll-wrap div.first-section.ng-isolate-scope div.table-container.box-paper table.tbl-border-light.tbl-striped tbody tr.ng-scope"

	# Resource Storage related
	ResDeposity_JobDone =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.screen-resource-deposit.twx-window.screen.left div.win-content.ng-scope div.win-main.resource-deposit.jssb-applied.jssb-focus.jssb-scrolly div.box-paper div.scroll-wrap div.ng-isolate-scope div.component-torn-paper.ng-scope div.content div.active-job div div.ng-scope div div.highlight-border a.btn-green.collect.animation-glow-green.ng-binding"
	ResDeposity_NewJob =	"html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper section.screen-resource-deposit.twx-window.screen.left div.win-content.ng-scope div.win-main.resource-deposit.jssb-applied.jssb-focus.jssb-scrolly div.box-paper div.scroll-wrap div.available-jobs table.job-cell.tbl-border-dark.ng-scope.job-active tbody tr.job-action td a.btn-orange.start-job.ng-binding"


	# Village DropDown related
	VillageDropdown_Menu = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper.window-open div#interface-top.ng-scope div.interface-wrapper div#top-wrapper div.info-wrapper div#info-town.info-box div#village-switch-buttons div.component-interface.ng-scope"


	# Map Canvas
	Map_Canvas = "html#twx.js.flexbox.canvas.canvastext.webgl.no-touch.geolocation.postmessage.no-websqldatabase.indexeddb.hashchange.history.draganddrop.websockets.rgba.hsla.multiplebgs.backgroundsize.borderimage.borderradius.boxshadow.textshadow.opacity.cssanimations.csscolumns.cssgradients.no-cssreflections.csstransforms.csstransforms3d.csstransitions.fontface.generatedcontent.video.audio.localstorage.sessionstorage.webworkers.applicationcache.svg.inlinesvg.smil.svgclippaths.pointerevents.canvasblending body.ng-scope div#wrapper div#map.ng-scope.running canvas#main-canvas"



